#!/bin/bash

PHPFCGI="php"
FCGIPORT="9000"
FCGIADDR="127.0.0.1"
PHP_FCGI_CHILDREN=5
PHP_FCGI_MAX_REQUESTS=1000
ALLOWED_ENV="ORACLE_HOME PATH USER"
USERID=www-data



################## no config below this line



if test x$PHP_FCGI_CHILDREN = x; then

  PHP_FCGI_CHILDREN=5

fi



ALLOWED_ENV="$ALLOWED_ENV PHP_FCGI_CHILDREN"

ALLOWED_ENV="$ALLOWED_ENV PHP_FCGI_MAX_REQUESTS"

ALLOWED_ENV="$ALLOWED_ENV FCGI_WEB_SERVER_ADDRS"



if test x$UID = x0; then

  EX="/bin/su -m -c \"$PHPFCGI -q -b $FCGIADDR:$FCGIPORT\" $USERID"

else

  EX="$PHPFCGI -b $FCGIADDR:$FCGIPORT"

fi



echo $EX



# copy the allowed environment variables

E=



for i in $ALLOWED_ENV; do

  E="$E $i=${!i}"

done



# clean environment and set up a new one

nohup env - $E sh -c "$EX" &> /dev/null &
