<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2008/10/13 21:51:58
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
